name: Build Direct2D Othello

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compile
        run: |
          cl.exe /O2 /MT /EHsc /std:c++17 main.cpp /Fe:Othello_Direct2D.exe user32.lib gdi32.lib d2d1.lib /link /SUBSYSTEM:WINDOWS
      - uses: actions/upload-artifact@v4
        with:
          name: Othello-D2D-Binary
          path: Othello_Direct2D.exe
